name: preprocessing

on:
  workflow_dispatch:
  push:
    paths:
      - "creditscoring_raw/**"
      - "preprocessing/**"

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn==1.6.0

      - name: Run preprocessing
        run: |
          python preprocessing/automate_EkoAndriPrasetyo.py             --input creditscoring_raw/creditscoring_raw.csv             --output preprocessing/creditscoring_preprocessing/creditscoring_preprocessed.csv

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-dataset
          path: preprocessing/creditscoring_preprocessing/creditscoring_preprocessed.csv
